# Generated by Django 5.2.17 on 2026-09-27 22:48

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Technician',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=150, verbose_name='nombre completo')),
                ('whatsapp_number', models.CharField(max_length=20, unique=True, verbose_name='número de WhatsApp')),
                ('is_active', models.BooleanField(default=True, verbose_name='activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='última actualización')),
            ],
            options={
                'verbose_name': 'técnico',
                'verbose_name_plural': 'técnicos',
                'db_table': 'technicians',
                'ordering': ['full_name'],
            },
        ),
    ]
