# Generated by Django 5.2.17 on 2026-09-27 22:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit', models.CharField(max_length=150, verbose_name='unidad')),
                ('equipment', models.CharField(max_length=150, verbose_name='equipo')),
                ('failure_type', models.CharField(max_length=100, verbose_name='tipo de falla')),
                ('description', models.TextField(verbose_name='descripción')),
                ('priority', models.CharField(choices=[('low', 'Baja'), ('medium', 'Media'), ('high', 'Alta'), ('critical', 'Crítica')], default='medium', max_length=20, verbose_name='prioridad')),
                ('status', models.CharField(choices=[('reported', 'Reportado'), ('under_review', 'En revisión'), ('in_progress', 'En progreso'), ('resolved', 'Resuelto'), ('closed', 'Cerrado'), ('cancelled', 'Cancelado')], default='reported', max_length=20, verbose_name='estado')),
                ('original_message', models.TextField(verbose_name='mensaje original')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='última actualización')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='fecha de resolución')),
                ('technician', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incidents', to='incidents.technician', verbose_name='técnico')),
            ],
            options={
                'verbose_name': 'incidente',
                'verbose_name_plural': 'incidentes',
                'db_table': 'incidents',
                'ordering': ['-created_at'],
            },
        ),
    ]
