# Generated by Django 5.2.17 on 2026-09-27 23:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0002_incident'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_message_id', models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='identificador externo')),
                ('phone_number', models.CharField(max_length=20, verbose_name='número de WhatsApp')),
                ('direction', models.CharField(choices=[('inbound', 'Recibido'), ('outbound', 'Enviado')], max_length=10, verbose_name='dirección')),
                ('message_type', models.CharField(choices=[('text', 'Texto'), ('audio', 'Audio'), ('image', 'Imagen'), ('document', 'Documento'), ('unknown', 'Desconocido')], default='text', max_length=20, verbose_name='tipo de mensaje')),
                ('content', models.TextField(blank=True, verbose_name='contenido')),
                ('raw_payload', models.JSONField(blank=True, default=dict, verbose_name='datos originales')),
                ('status', models.CharField(choices=[('received', 'Recibido'), ('processing', 'Procesando'), ('processed', 'Procesado'), ('sent', 'Enviado'), ('delivered', 'Entregado'), ('read', 'Leído'), ('failed', 'Fallido')], default='received', max_length=20, verbose_name='estado')),
                ('error_message', models.TextField(blank=True, verbose_name='detalle del error')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='fecha de procesamiento')),
                ('incident', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='incidents.incident', verbose_name='incidente')),
                ('technician', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='incidents.technician', verbose_name='técnico')),
            ],
            options={
                'verbose_name': 'mensaje de WhatsApp',
                'verbose_name_plural': 'mensajes de WhatsApp',
                'db_table': 'whatsapp_messages',
                'ordering': ['created_at'],
            },
        ),
    ]
