# Generated by Django 5.2.17 on 2026-09-27 23:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0003_whatsappmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncidentDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('collecting', 'Recopilando información'), ('ready', 'Información completa'), ('completed', 'Incidente creado'), ('expired', 'Expirado'), ('cancelled', 'Cancelado')], default='collecting', max_length=20, verbose_name='estado')),
                ('extracted_data', models.JSONField(blank=True, default=dict, verbose_name='datos extraídos')),
                ('missing_fields', models.JSONField(blank=True, default=list, verbose_name='campos faltantes')),
                ('last_question', models.TextField(blank=True, verbose_name='última pregunta realizada')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='última actualización')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='fecha de expiración')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='fecha de finalización')),
                ('incident', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_draft', to='incidents.incident', verbose_name='incidente creado')),
                ('initial_message', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='started_draft', to='incidents.whatsappmessage', verbose_name='mensaje inicial')),
                ('technician', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incident_drafts', to='incidents.technician', verbose_name='técnico')),
            ],
            options={
                'verbose_name': 'borrador de incidente',
                'verbose_name_plural': 'borradores de incidentes',
                'db_table': 'incident_drafts',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.AddField(
            model_name='whatsappmessage',
            name='draft',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='incidents.incidentdraft', verbose_name='borrador'),
        ),
        migrations.AddConstraint(
            model_name='incidentdraft',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['collecting', 'ready'])), fields=('technician',), name='unique_active_draft_per_technician'),
        ),
    ]
